### PR TITLE
Update addon to latest Ember LTS(3.8.x). 

### LINKED ISSUE #9: ember-cli-babel 5.x has been deprecated. Can we create a new Release ?
Hello @williamsbdev ,

WDYT about a new release?

kind regards

### PR DESCRIPTION
**Pull request by wuarmin**
Hey,
This would fix #9 
I updated the addon to Ember 3.8, fixed ember try config and travis.yml.

At CI I switched to yarn, because ember try and npm doesn't cooperate at the moment. But that should not be an issue.

I will check, if further improvements can be made (codemods, update readme, etc.) 

WDYT?

### CODE REVIEW

**Comment by williamsbdev** [comment]
@wuarmin - This looks great! Thank you for the PR.

**Comment by williamsbdev** [comment]
@wuarmin - a new version (2.1.0) has been published. Thanks again for your help updating this!

**Comment by wuarmin** [comment]
@williamsbdev thank you. could you also add a tag 2.1.0?

**Comment by williamsbdev** [comment]
@wuarmin - Good call! Just did that.

**Pull request merged**
